---
title: Reordering bars in GGanimate visualization
author: Carlos Vecina Tebar
date: "2019-12-17"
slug: reorder-bars-gganimate
translationKey: "reorder-bars-gganimate"
output:
  blogdown::html_page:
    highlight: tango
categories:
- R
- Tips
- Ggplot
tags: []
subtitle: ''
summary: "Reorder your groups over time in gganimate plot."
authors: [carlos-vecina]
featured: false
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval=FALSE}
library(ggplot2)
library(gganimate)
library(tidyverse)
df_evolution_data <- data.frame(Name=rep(c("Madrid","Barcelona",
                              "Valencia","Alicante",
                              "Sevilla"),5),
                   Year = factor(sort(rep(2001:2005, 5))),
                   Value = runif(25,100,1000))
df_evolution_data_filtered <- df_evolution_data %>%
  group_by(Year) %>%
  mutate(Rank = rank(Value)) %>% 
  filter(Rank >= 2)
```

```{r, eval=FALSE}
ggplot(df_evolution_data_filtered) +
  geom_col(aes(x=Rank, y=Value, group=Name, fill=Name), width=0.4) +
  geom_text(aes(x=Rank, y=0, label=Name, group=Name), hjust=1.25) +
  theme_minimal() + ylab('Value') +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        plot.margin = unit(c(5,5,5,5), 'lines')) +
  scale_fill_brewer(palette="Dark2") +
  coord_flip(clip='off') + 
  ggtitle('{closest_state}') + 
  transition_states(Year, transition_length = 1, state_length = 1) +
  exit_fly(x_loc = 0, y_loc = 0) + enter_fly(x_loc = 0, y_loc = 0)
```

