---
title: "Using summarise_at(). Weighted mean Tidyverse approach"
author: "Carlos Vecina Tebar"
date: "2020-01-16"
slug: "summarise_at-weighted-mean-tidyverse-R"
translationKey: "summarise_at-media-ponderada-tidyverse-R"
output:
  blogdown::html_page:
    highlight: tango
categories:
- R
- Tips
tags: [Tidyverse]
subtitle: 'Survey analysis using R. Mastering Tidyverse summarise_at() function to achieve aggregated metrics and statistics.'
summary: "Survey analysis using R"
authors: [carlos-vecina]
featured: false
draft: false
disable_codefolding: true

---

```{r, include=FALSE}
nchar("Survey analysis using R. Mastering Tidyverse summarise_at() function to achieve aggregated metrics and statistics.")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Supose you are analysing survey data. You are asked to get the mean in a representative way, weighting your individuals depending on the number of members of their segment. 

```{r, warning=FALSE, message=FALSE}
library(tidyverse)

survey_data <- tribble(
  ~id, ~region1, ~region2, ~gender, ~q1, ~q2,
  1,"sp","mad","m", 2,5,
  2,"it", "bol", "m", 5, 10,
  3,"sp", "bar", "f", 2, 2,
  4,"sp", "bar", "f", 7, 7,
  5,"it", "bol", "m", 2, 7)  
```

```{r, warning=FALSE, eval=FALSE}
  survey_data %>% 
  group_by(region1, region2, gender) %>% 
  mutate(weight = 1/n()) %>% 
  ungroup() %>% 
  summarise_at(vars(contains("q")),
               funs(weighted_mean = sum(. * weight)/sum(weight)))
```

```{r, warning=FALSE, echo=FALSE, message=FALSE}
library(knitr)
library(kableExtra)
  survey_data %>% 
  group_by(region1, region2, gender) %>% 
  mutate(weight = 1/n()) %>% 
  ungroup() %>% 
  summarise_at(vars(contains("q")),  funs(weighted_mean = sum(. * weight)/sum(weight))) %>% 
    kable() %>% 
  kable_styling(bootstrap_options = "striped", full_width = F)
```

