---
title: Muestra tus habilidades o *skills mediante un gráfico en R y su paquete Ggplot
author: Carlos Vecina Tebar
date: "2020-01-07"
slug: skills-chart-curriculum
translationKey: "skills-chart"
output:
  blogdown::html_page:
    highlight: tango
categories:
- R
- Vizs
- Ggplot2
tags: []
subtitle: ''
summary: "Gráfico de habilidades con 2 lineas de Ggplot R."
authors: [carlos-vecina]
featured: false
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Puedes ver el código en el siguiente *chunk*:

```{r, warning=FALSE, message=FALSE}
library(ggplot2)
# library(plotly)
library(tibble)
library(dplyr)

skills <- tribble(
    ~ Skill, ~ Hours, ~ Class,
    "AWS", 500, "BigData",
    "Python", 8000, "Language",
    "Spark", 4000, "BigData",
    "R", 9000, "Language",
    "Git", 2000, "Tools",
    "Jira", 2000, "Tools",
    "Forecasting", 5000, "Objetive",
    "Segmentation", 2000, "Objetive",
    "Computer Vision", 600, "Objetive",
    "SQL", 4500, "Language",
    "IBM Data Stage & SPSS", 1200, "Tools",
    "Shiny R", 1500, "Visualization",
    "Tableau", 1000, "Visualization",
    "Spotfire", 500, "Visualization"
) 
```


```{r, skills-plot, warning=FALSE, eval=FALSE}
# plotly(
ggplot(data=skills,aes(x=reorder(Skill,-desc(Hours)), y= Hours, fill=Class, label=paste0(Hours," h"))) + 
    geom_bar(stat = "identity", colour="black") +
    coord_flip() +
    labs(x=" ", y="Hours", fill=" ")  +
    theme_minimal() +
    scale_fill_brewer(palette = "YlOrBr",direction = -1) +
    geom_label(show_guide  = F, aes(y=400))                  # Use show_guide despite the warning

```

